/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

/**
 *
 * @author ThanhAn
 */
public class PhepToan_Radio extends javax.swing.JFrame {

    /**
     * Creates new form PhepToan_Radio
     */
    public PhepToan_Radio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrPhepToan = new javax.swing.ButtonGroup();
        lbA = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        lbB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtKQ = new javax.swing.JTextField();
        rdCong = new javax.swing.JRadioButton();
        rdTru = new javax.swing.JRadioButton();
        rdNhan = new javax.swing.JRadioButton();
        rdChia = new javax.swing.JRadioButton();
        btnTinh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Các Phép Tính Toán");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbA.setText("A = ");
        getContentPane().add(lbA, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 27, 40, 25));

        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 190, 25));
        getContentPane().add(txtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 190, 25));

        lbB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbB.setText("B = ");
        getContentPane().add(lbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 63, 40, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Kết quả");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtKQ.setEditable(false);
        getContentPane().add(txtKQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 190, 28));

        btngrPhepToan.add(rdCong);
        rdCong.setText("+");
        getContentPane().add(rdCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        btngrPhepToan.add(rdTru);
        rdTru.setText("-");
        getContentPane().add(rdTru, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        btngrPhepToan.add(rdNhan);
        rdNhan.setText("*");
        getContentPane().add(rdNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        btngrPhepToan.add(rdChia);
        rdChia.setText("/");
        getContentPane().add(rdChia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        btnTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTinh.setText("Tính");
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });
        getContentPane().add(btnTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAActionPerformed

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        // TODO add your handling code here:
        double a = Double.parseDouble(txtA.getText());
        double b = Double.parseDouble(txtB.getText());
        if(rdCong.isSelected())
            txtKQ.setText(String.valueOf(a+b));
        if(rdTru.isSelected())
            txtKQ.setText(String.valueOf(a-b));
        if(rdNhan.isSelected())
            txtKQ.setText(String.valueOf(a*b));
        if(rdChia.isSelected())
            txtKQ.setText(String.valueOf(a/b));
    }//GEN-LAST:event_btnTinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhepToan_Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhepToan_Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhepToan_Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhepToan_Radio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhepToan_Radio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinh;
    private javax.swing.ButtonGroup btngrPhepToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbA;
    private javax.swing.JLabel lbB;
    private javax.swing.JRadioButton rdChia;
    private javax.swing.JRadioButton rdCong;
    private javax.swing.JRadioButton rdNhan;
    private javax.swing.JRadioButton rdTru;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtKQ;
    // End of variables declaration//GEN-END:variables
}
