/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai3;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author ThanhAn
 */
public class Bai3 extends javax.swing.JFrame {

  
    public Bai3() {
        initComponents();
        addListTrai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lsTrai = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsPhai = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnChuyenPhai1 = new javax.swing.JButton();
        btnChuyenPhaiTatCa = new javax.swing.JButton();
        btnChuyenTrai1 = new javax.swing.JButton();
        btnChuyenTraiTatCa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LISTVIEW BAI 3");

        lsTrai.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Đá Bóng", "Cờ Vua", "Bóng Chuyền", "Bơi Lội", "Cầu Lông" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lsTrai);

        jScrollPane2.setViewportView(lsPhai);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Danh sách môn thể thao");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Môn yêu thích");

        btnChuyenPhai1.setText(">");
        btnChuyenPhai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenPhai1ActionPerformed(evt);
            }
        });

        btnChuyenPhaiTatCa.setText(">>");
        btnChuyenPhaiTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenPhaiTatCaActionPerformed(evt);
            }
        });

        btnChuyenTrai1.setText("<");
        btnChuyenTrai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenTrai1ActionPerformed(evt);
            }
        });

        btnChuyenTraiTatCa.setText("<<");
        btnChuyenTraiTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenTraiTatCaActionPerformed(evt);
            }
        });

        btnThem.setText("+");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnChuyenPhaiTatCa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnChuyenTraiTatCa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChuyenPhai1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChuyenTrai1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnChuyenPhai1)
                        .addGap(27, 27, 27)
                        .addComponent(btnChuyenPhaiTatCa)
                        .addGap(27, 27, 27)
                        .addComponent(btnChuyenTrai1)
                        .addGap(27, 27, 27)
                        .addComponent(btnChuyenTraiTatCa)))
                .addGap(18, 18, 18)
                .addComponent(btnThem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArrayList <String> arrTrai= new ArrayList<>();
    ArrayList <String> arrPhai = new ArrayList<>();
    public void addListTrai(){
        ListModel mTrai = lsTrai.getModel();
        
        for (int i=0; i< mTrai.getSize(); i++){
            String ten = mTrai.getElementAt(i).toString();
            arrTrai.add(ten);
        }
    }
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String sThem = JOptionPane.showInputDialog(null, "Nhập môn thể thao mới", "Môn thể thao", JOptionPane.INFORMATION_MESSAGE);
        arrTrai.add(sThem);
        String[] aTen = arrTrai.toArray(new String[arrTrai.size() + 1]);
        lsTrai.setListData(aTen);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnChuyenPhai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenPhai1ActionPerformed
        // TODO add your handling code here:
        int iStt = lsTrai.getSelectedIndex();
        ListModel mTrai = lsTrai.getModel();
        String sChon = mTrai.getElementAt(iStt).toString();
        
        //Xóa item đã chọn bên list trái
        for (String n : arrTrai){
            if(sChon.equals(n)){
                arrTrai.remove(sChon);
                break;
            }
        }
        String[] aTenTrai = arrTrai.toArray(new String[arrTrai.size()+1]);
        lsTrai.setListData(aTenTrai);
        
        //Thêm vào list phải
        arrPhai.add(sChon);
        String[] aTenPhai = arrPhai.toArray(new String[arrPhai.size()+1]);
        lsPhai.setListData(aTenPhai);
    }//GEN-LAST:event_btnChuyenPhai1ActionPerformed

    private void btnChuyenPhaiTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenPhaiTatCaActionPerformed
        // TODO add your handling code here:
        
        for (String n : arrTrai){
            arrPhai.add(n);
        }
        String[] aTenPhai = arrPhai.toArray(new String[arrPhai.size()+1]);
        lsPhai.setListData(aTenPhai);
        
        //Xóa tất cả item bên list trái
        arrTrai.clear();
        String[] aTenTrai = arrTrai.toArray(new String[arrTrai.size()+1]);
        lsTrai.setListData(aTenTrai);
    }//GEN-LAST:event_btnChuyenPhaiTatCaActionPerformed

    private void btnChuyenTrai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenTrai1ActionPerformed
        // TODO add your handling code here:
        ListModel mPhai = lsPhai.getModel();

        int iStt = lsPhai.getSelectedIndex();
        //ListModel mPhai = lsPhai.getModel();
        String sChon = mPhai.getElementAt(iStt).toString();
        
        //Xóa item đã chọn bên list phải
        for (String n : arrPhai){
            if(sChon.equals(n)){
                arrPhai.remove(sChon);
                break;
            }
        }
        String[] aTenPhai = arrPhai.toArray(new String[arrPhai.size()+1]);
        lsPhai.setListData(aTenPhai);
        
        //Thêm vào list trái
        arrTrai.add(sChon);
        String[] aTenTrai = arrTrai.toArray(new String[arrTrai.size()+1]);
        lsTrai.setListData(aTenTrai);
    }//GEN-LAST:event_btnChuyenTrai1ActionPerformed

    private void btnChuyenTraiTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenTraiTatCaActionPerformed
        // TODO add your handling code here:
        for (String n : arrPhai){
            arrTrai.add(n);
        }
        String[] aTenTrai = arrTrai.toArray(new String[arrTrai.size()+1]);
        lsTrai.setListData(aTenTrai);
        
        //Xóa tất cả item bên list phải
        arrPhai.clear();
        String[] aTenPhai = arrPhai.toArray(new String[arrPhai.size()+1]);
        lsPhai.setListData(aTenPhai);
    }//GEN-LAST:event_btnChuyenTraiTatCaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChuyenPhai1;
    private javax.swing.JButton btnChuyenPhaiTatCa;
    private javax.swing.JButton btnChuyenTrai1;
    private javax.swing.JButton btnChuyenTraiTatCa;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lsPhai;
    private javax.swing.JList<String> lsTrai;
    // End of variables declaration//GEN-END:variables
}
