/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitaprenluyen;

import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThanhAn
 */
public class BaiTap89 extends javax.swing.JFrame {

    /**
     * Creates new form BaiTap89
     */
    public BaiTap89() {
        initComponents();
        
        tableTitle.add("Mã nhân viên");
        tableTitle.add("Phân xưởng");
        tableTitle.add("Số sản phẩm");
        tableTitle.add("Vượt chuẩn");
        tbNhanVien.setModel(new DefaultTableModel(tableRecords, tableTitle));
    }
    
    public void Clear_All(){
        txtMaNv.setText("");
        txtSoSp.setText("");
        txtSpChuan.setText("300");
        txtTienLuong.setText("");
        cbbPhanXuong.setSelectedItem("A");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaNv = new javax.swing.JTextField();
        txtSoSp = new javax.swing.JTextField();
        cbbPhanXuong = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSpChuan = new javax.swing.JTextField();
        txtTienLuong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        btnTinhLuong = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NHẬP THÔNG TIN NHÂN VIÊN");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Mã NV");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Số sản phẩm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Phân xưởng");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Tiền lương");

        cbbPhanXuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        cbbPhanXuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPhanXuongActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Số sản phẩm chuẩn");

        txtSpChuan.setEditable(false);
        txtSpChuan.setText("300");

        txtTienLuong.setEditable(false);

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNhanVien);

        btnTinhLuong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTinhLuong.setText("Tính Lương");
        btnTinhLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhLuongActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnDong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDong.setText("Đóng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSoSp, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                        .addComponent(cbbPhanXuong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMaNv))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addGap(48, 48, 48)
                                    .addComponent(txtSpChuan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtTienLuong))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTinhLuong)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addGap(18, 18, 18)
                        .addComponent(btnDong)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaNv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtSoSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbPhanXuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtSpChuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinhLuong)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnDong))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public class NhanVien{
        private String MaNhanVien;
        private String PhanXuong;
        private int SoSp;
        public NhanVien(){
            MaNhanVien = "";
            PhanXuong = "";
            SoSp = 0;
        }

        /**
         * @return the MaNhanVien
         */
        public String getMaNhanVien() {
            return MaNhanVien;
        }

        /**
         * @param MaNhanVien the MaNhanVien to set
         */
        public void setMaNhanVien(String MaNhanVien) {
            this.MaNhanVien = MaNhanVien;
        }

        /**
         * @return the PhanXuong
         */
        public String getPhanXuong() {
            return PhanXuong;
        }

        /**
         * @param PhanXuong the PhanXuong to set
         */
        public void setPhanXuong(String PhanXuong) {
            this.PhanXuong = PhanXuong;
        }

        /**
         * @return the SoSp
         */
        public int getSoSp() {
            return SoSp;
        }

        /**
         * @param SoSp the SoSp to set
         */
        public void setSoSp(int SoSp) {
            this.SoSp = SoSp;
        }
        
        public int getChuan(){
            if (PhanXuong == "A"){
                return 300;
            }
            else
                return 500;
        }
        
        public Boolean VuotChuan(){
            SoSp = Integer.parseInt(txtSoSp.getText());
            if (SoSp > getChuan()){
                return true;
            }
            else
                return false;
        }
        
        public double TinhLuong(){
            int DonGia;
            //int SoSp = Integer.parseInt(txtSoSp.getText());
            if (VuotChuan())
                DonGia = 30000;
            else
                DonGia = 20000;
            return SoSp * DonGia;
        }
        
        public String toString(){
            return MaNhanVien;
        }
    }
    NhanVien nv = new NhanVien();
    
    private void cbbPhanXuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbPhanXuongActionPerformed
        // TODO add your handling code here:
        
        nv.setPhanXuong(cbbPhanXuong.getSelectedItem().toString());
        txtSpChuan.setText(String.valueOf(nv.getChuan()));
    }//GEN-LAST:event_cbbPhanXuongActionPerformed

    private void btnTinhLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhLuongActionPerformed
        // TODO add your handling code here:
        try {
            nv.setMaNhanVien(txtMaNv.getText());
            nv.setSoSp(Integer.parseInt(txtSoSp.getText()));
            txtTienLuong.setText(String.valueOf(nv.TinhLuong()));
        } catch (Exception e) {
            String t = "";
            if (t.equals(txtMaNv.getText()))
                JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã nhân viên");
            if (t.equals(txtSoSp.getText()))
                JOptionPane.showMessageDialog(null, "Bạn chưa nhập số sản phẩm");
            else
                JOptionPane.showMessageDialog(null, "Số sản phẩm phải là số");
        }
    }//GEN-LAST:event_btnTinhLuongActionPerformed
    Vector tableRecords = new Vector(); //Vector chứa các dòng dữ liệu của bảng.
    Vector tableTitle = new Vector(); //Vector chứa các tiêu đề của bảng.
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            nv.setMaNhanVien(txtMaNv.getText());
            nv.setSoSp(Integer.parseInt(txtSoSp.getText()));
            nv.setPhanXuong(cbbPhanXuong.getSelectedItem().toString());
            
            String getVuotChuan = "";
            if (nv.VuotChuan())
                getVuotChuan = "x";
            
            Vector record = new Vector();
            record.add(txtMaNv.getText());
            record.add(cbbPhanXuong.getSelectedItem());
            record.add(txtSoSp.getText());
            record.add(getVuotChuan);
            tableRecords.add(record);
            tbNhanVien.setModel(new DefaultTableModel(tableRecords, tableTitle));
            
            Clear_All();
        } catch (Exception e) {
            String t = "";
            if (t.equals(txtMaNv.getText()))
                JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã nhân viên");
            if (t.equals(txtSoSp.getText()))
                JOptionPane.showMessageDialog(null, "Bạn chưa nhập số sản phẩm");
            else
                JOptionPane.showMessageDialog(null, "Số sản phẩm phải là số");
        }
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int iDongDaChon = tbNhanVien.getSelectedRow();
            if (iDongDaChon == -1) {
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn record cần xóa");
            } else {
                Vector vDongDaChon = (Vector) tableRecords.get(iDongDaChon);
                String MaNvCuaDongDaChon = vDongDaChon.get(0).toString();
                if (JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa dòng đã chọn có mã nv: " + MaNvCuaDongDaChon, "Lựa chọn", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    tableRecords.remove(iDongDaChon);
                    tbNhanVien.setModel(new DefaultTableModel(tableRecords, tableTitle));
                }
            }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int iDongDaChon = tbNhanVien.getSelectedRow();
            if (iDongDaChon == -1) {
                JOptionPane.showMessageDialog(rootPane, "Xin vui lòng chọn dòng cần sửa");
            } else {
                String getVuotChuan = "";
                if (nv.VuotChuan())
                    getVuotChuan = "x";
                
                Vector record = new Vector();
                record.add(txtMaNv.getText());
                record.add(cbbPhanXuong.getSelectedItem());
                record.add(txtSoSp.getText());
                record.add(getVuotChuan);
                tableRecords.set(iDongDaChon, record);
                tbNhanVien.setModel(new DefaultTableModel(tableRecords, tableTitle));
                Clear_All();
            }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMouseClicked
        // TODO add your handling code here:
        int iDongDaChon = tbNhanVien.getSelectedRow();
            if (iDongDaChon != -1) {
                Vector vDongDaChon = (Vector) tableRecords.get(iDongDaChon);
                String Manv = vDongDaChon.get(0).toString();
                String Px = vDongDaChon.get(1).toString();
                String Sp = vDongDaChon.get(2).toString();
                //txtSpChuan.setText(String.valueOf(nv.getChuan()));
                txtMaNv.setText(Manv);
                txtSoSp.setText(Sp);
                cbbPhanXuong.setSelectedItem(Px);
                txtTienLuong.setText(String.valueOf(nv.TinhLuong()));
            }
    }//GEN-LAST:event_tbNhanVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaiTap89.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaiTap89.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaiTap89.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaiTap89.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaiTap89().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbPhanXuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTextField txtMaNv;
    private javax.swing.JTextField txtSoSp;
    private javax.swing.JTextField txtSpChuan;
    private javax.swing.JTextField txtTienLuong;
    // End of variables declaration//GEN-END:variables
}
