/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PL;

import javax.swing.JFrame;

/**
 *
 * @author ThanhAn
 */
public class MenuPL extends javax.swing.JFrame {

    /**
     * Creates new form MenuPL
     */
    public MenuPL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTaiKhoan = new javax.swing.JMenu();
        jMenuQuanLyTaiKhoan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuKhachHang = new javax.swing.JMenuItem();
        jMenuXe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuTaiKhoan.setText("Tài Khoản");

        jMenuQuanLyTaiKhoan.setText("Quản lý tài khoản");
        jMenuQuanLyTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuanLyTaiKhoanActionPerformed(evt);
            }
        });
        jMenuTaiKhoan.add(jMenuQuanLyTaiKhoan);

        jMenuBar1.add(jMenuTaiKhoan);

        jMenu2.setText("Quản Lý");

        jMenuKhachHang.setText("Khách Hàng");
        jMenuKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuKhachHangActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuKhachHang);

        jMenuXe.setText("Xe");
        jMenuXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuXeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuXe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuQuanLyTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuanLyTaiKhoanActionPerformed
        // TODO add your handling code here:
        QuanLyTaiKhoanPL ql = new QuanLyTaiKhoanPL();
        ql.setLocationRelativeTo(null);
        ql.setVisible(true);
        ql.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuQuanLyTaiKhoanActionPerformed

    private void jMenuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuKhachHangActionPerformed
        // TODO add your handling code here:
        KhachHangPL kh = new KhachHangPL();
        kh.setLocationRelativeTo(null);
        kh.setVisible(true);
        kh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuKhachHangActionPerformed

    private void jMenuXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuXeActionPerformed
        // TODO add your handling code here:
        XePL x = new XePL();
        x.setLocationRelativeTo(null);
        x.setVisible(true);
        x.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuXeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuKhachHang;
    private javax.swing.JMenuItem jMenuQuanLyTaiKhoan;
    private javax.swing.JMenu jMenuTaiKhoan;
    private javax.swing.JMenuItem jMenuXe;
    // End of variables declaration//GEN-END:variables
}
