/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PL;

import BLL.XeBLL;
import DTO.XeDTO;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author ThanhAn
 */
public class XePL extends javax.swing.JFrame {

    XeBLL xeBll = new XeBLL();
    /**
     * Creates new form XePL
     */
    public XePL() {
        initComponents();
        xeBll.LoadDSXe(tbXe);
        xeBll.LoadCbbTenLoai(cbbTenLoai);
       
    }

    public void Clear_ALL(){
        txtSoXe.setText("");
        rbXeCu.setSelected(true);
        xeBll.LoadCbbTenLoai(cbbTenLoai);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grTinhTrang = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbXe = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoXe = new javax.swing.JTextField();
        rbXeCu = new javax.swing.JRadioButton();
        rbXeMoi = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        cbbTenLoai = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("XE");

        tbXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbXeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbXe);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Số xe");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tình trạng");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên loại");

        grTinhTrang.add(rbXeCu);
        rbXeCu.setSelected(true);
        rbXeCu.setText("Xe cũ");

        grTinhTrang.add(rbXeMoi);
        rbXeMoi.setText("Xe mới");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbXeCu)
                                .addGap(18, 18, 18)
                                .addComponent(rbXeMoi))
                            .addComponent(txtSoXe)
                            .addComponent(cbbTenLoai, 0, 132, Short.MAX_VALUE))))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSoXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem)
                    .addComponent(btnSua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbXeCu)
                    .addComponent(rbXeMoi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnDong)
                    .addComponent(jLabel3)
                    .addComponent(cbbTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (txtSoXe.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập số xe.");
        }
        else{
            try {
                if(xeBll.getTrungMa(txtSoXe.getText())){
                    JOptionPane.showMessageDialog(null, "Số xe bị trùng.");
                }
                else{
                    String soxe = txtSoXe.getText();
                    String tinhtrang = "";
                    if(rbXeCu.isSelected()){
                        tinhtrang = "0";
                    }
                    else
                        tinhtrang = "1";
                    //String maloai = cbbTenLoai.getSelectedItem().toString();
                    String maloai = String.valueOf(xeBll.getValueComboBoxTenLoai(cbbTenLoai));
                    XeDTO xe = new XeDTO(soxe, tinhtrang, maloai);
                    if (xeBll.ThemXe(xe)){
                        xeBll.LoadDSXe(tbXe);
                        Clear_ALL();
                        JOptionPane.showMessageDialog(null, "Thêm thành công.");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Thêm không thành công.");
                    }
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int iDongDaChon = tbXe.getSelectedRow();
        if (iDongDaChon == -1){
            JOptionPane.showMessageDialog(null, "Mời chọn 1 khách hàng.");
        }
        else{
            try {
                if(JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa xe: \"" + txtSoXe.getText().toUpperCase() + "\" không?", "Thông Báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                    try {
                        if(xeBll.XoaXe(txtSoXe.getText())){
                            xeBll.LoadDSXe(tbXe);
                            Clear_ALL();
                            JOptionPane.showMessageDialog(null, "Xóa thành công.");
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Xóa không thành công.");
                        }
                    } catch (Exception e) {
                    }
                }
            } catch (Exception e) {
            }
        }
        //lb.setText(String.valueOf(xeBll.getComboboxValue(cbbTenLoai)));
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tbXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbXeMouseClicked
        // TODO add your handling code here:
        int iDongDaChon = tbXe.getSelectedRow();
        TableModel model = tbXe.getModel();
        
        txtSoXe.setText(model.getValueAt(iDongDaChon, 0).toString());
        if(model.getValueAt(iDongDaChon, 1) == "Xe cũ"){
            rbXeCu.setSelected(true);
        }
        else
            rbXeMoi.setSelected(true);
        cbbTenLoai.setSelectedItem(model.getValueAt(iDongDaChon, 2).toString());
    }//GEN-LAST:event_tbXeMouseClicked

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (txtSoXe.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Chọn số xe để sửa");
        }
        else{
            try {
                String soxe = txtSoXe.getText();
                String tinhtrang = "";
                if(rbXeCu.isSelected()){
                    tinhtrang = "0";
                }
                else
                    tinhtrang = "1";
                //String maloai = cbbTenLoai.getSelectedItem().toString();
                String maloai = String.valueOf(xeBll.getValueComboBoxTenLoai(cbbTenLoai));
                XeDTO xe = new XeDTO(soxe, tinhtrang, maloai);
                if (xeBll.SuaXe(xe)){
                    xeBll.LoadDSXe(tbXe);
                    Clear_ALL();
                    JOptionPane.showMessageDialog(null, "Sửa thành công.");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Sửa không thành công.");
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XePL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XePL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XePL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XePL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                XePL xe = new XePL();
                xe.setLocationRelativeTo(null);
                xe.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbTenLoai;
    private javax.swing.ButtonGroup grTinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbXeCu;
    private javax.swing.JRadioButton rbXeMoi;
    private javax.swing.JTable tbXe;
    private javax.swing.JTextField txtSoXe;
    // End of variables declaration//GEN-END:variables
}
